# Generated by Django 4.2 on 2025-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_extensao', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('horas', models.IntegerField()),
                ('situacao', models.CharField(choices=[('submetidas', 'Em análise'), ('integralizadas', 'Integralizada'), ('indeferidas', 'Indeferida')], default='Em análise', max_length=20)),
            ],
        ),
    ]
