# Generated by Django 4.2 on 2025-02-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_remove_atividade_data_avaliacao_atividade_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(choices=[('Em análise', 'Em análise'), ('Integralizada', 'Integralizada'), ('Indeferida', 'Indeferida')], default='Em análise', max_length=20),
        ),
    ]
