# Generated by Django 4.2 on 2025-02-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_atividade_situacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='tipo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_curso',
            field=models.CharField(blank=True, choices=[('Formação inicial', 'Formação inicial'), ('Formação continuada', 'Formação continuada')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_evento',
            field=models.CharField(blank=True, choices=[('Congresso', 'Congresso'), ('Seminário', 'Seminário'), ('Encontro', 'Encontro'), ('Simpósio', 'Simpósio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='acao_extensao',
            field=models.CharField(choices=[('Programa', 'Programa'), ('Projeto', 'Projeto'), ('Curso', 'Curso'), ('Evento', 'Evento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horas',
            field=models.PositiveIntegerField(),
        ),
    ]
