# Generated by Django 4.2 on 2025-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_remove_atividade_tipo_atividade_tipo_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='situacao',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='acao_extensao',
            field=models.CharField(choices=[('Programa', 'Programa'), ('Projeto', 'Projeto'), ('Curso', 'Curso'), ('Evento', 'Evento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo_curso',
            field=models.CharField(blank=True, choices=[('Formação inicial', 'Formação inicial'), ('Formação continuada', 'Formação continuada')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo_evento',
            field=models.CharField(blank=True, choices=[('Congresso', 'Congresso'), ('Seminário', 'Seminário'), ('Encontro', 'Encontro'), ('Simpósio', 'Simpósio')], max_length=30, null=True),
        ),
    ]
