# Generated by Django 4.2 on 2025-02-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0005_remove_atividade_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='situacao',
            field=models.CharField(default='Em análise', max_length=50),
        ),
    ]
